### ISSUE TITLE
Use a polyfill for WeakMap for older browsers

### ISSUE THREAD

**Issue by Elhebert** [FineUploader/fine-uploader-wrappers#1]
Currently writing my unit tests, and came accros an issue with `callback-proxy.js`.

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: WeakMap
  at webpack:///~/fine-uploader-wrappers/callback-proxy.js:19:0 <- index.js:27812
```

I know it's not an issue per se, because PhantomJS don't know WeakMap (I'm currently looking for a polyfill), but since fine-uploader is supposed to be compatible with IE8+, it might be a good idea to add a polyfill when it's not available for a given browser.

**Comment by rnicholus** [comment]
A couple things:
- React Fine Uploader and all newer libraries in this org that wrap Fine Uploader or extend it should only be targeting newer browsers: IE11 and up.
- I'll be removing support for all browsers older than IE11 in fine-uploader in v6.0.

I stopped using phantom a long time ago, it's too much of a hassle. Better to test against real browsers anyway.


Time to move forward and leave old browsers behind!
