### ISSUE TITLE
UI API not exposed

### ISSUE THREAD

**Issue by dineshpannu** [FineUploader/fine-uploader-wrappers#11]
I need access to getItemByFileId() in the UI API but it doesn't seem to be exposed by fine-uploader-wrappers. The UI API is everything from addExtraDropzone() down on the Traditional API page.

https://docs.fineuploader.com/branch/master/api/methods.html#addExtraDropzone

I'm assuming this in a fine-uploader-wrappers issue as it creates the .methods property.

**Comment by rnicholus** [comment]
There is no UI API to expose, because there is no UI. The expectation is that you build your own UI to fit your app using the core features of Fine Uploader.
