### ISSUE TITLE
Access to UI methods

### ISSUE THREAD

**Issue by ramusus** [FineUploader/fine-uploader-wrappers#7]
Hi, guys!

How I can access API UI methods, for example [addExtraDropzone](https://docs.fineuploader.com/branch/master/api/methods.html#addExtraDropzone) etc.
I see there are only API Core methods accessible via `provider.methods.xxx`

**Comment by rnicholus** [comment]
You can't. This is core only - you'll need to build your own UI, use React Fine Uploader, or Vue Fine Uploader

**Comment by ramusus** [comment]
Thanks @rnicholus
